### ISSUE TITLE
Request: Pug loader

### ISSUE THREAD

**Issue by jcayzac** [stackbithq/unibit#27]
[Pug](https://pugjs.org/)'s syntax is less verbose than Nunjucks and has very similar features. It would be nice if unibit supported themes written using Pug templates.

**Comment by smnh** [comment]
The reason we built Unibit is to allow Stackbit to transpile themes/sites written in Unibit/Nunjucks to other static site generators like Gatsby, Next.js, Hugo and Jekyll.

<p align="center"><img width="500" src="https://user-images.githubusercontent.com/97896/109133195-6bd95080-775d-11eb-9c57-d8cd935add23.png""></p>

Behind the scenes, Stackbit parses Nunjuck templates and compiles them to other languages like React (Gatsby, Next.js), Go (Hugo) and Liquid (Jekyll).

Adding another template language to Unibit like Pug, will add additional complexity to be able to parse Pug and compile it to languages listed above. Otherwise, Unibit themes written with Pug will not be convertible to other static-site-generators which contradicts the main concept for which we created Unibit.
